### ISSUE TITLE
dynamic hostname retrieval

### ISSUE THREAD

**Issue by Mausy5043** [bartsmit/opnsense-update-email#1]
https://github.com/bartsmit/opnsense-update-email/blob/82d1b7b4587e9a4d666d8213072ecbe1acc6285f/fw_update-1.2.py#L23

You might want to consider this instead:
```
import os
NODE        = os.uname()[1]
```

BTW, great idea. Hope you don't mind me using it.

**Comment by bartsmit** [comment]
That will return the hostname of the machine the python script is running from. This is not necessarily the firewall since the idea is for an external server to check the firewall.

You're absolutely more than welcome to use all or any part of the script. That's what github is for ;-)

Bart...

**Comment by Mausy5043** [comment]
Ah, it's supposed to run on a client! I thought it should be run from the firewall.
Thanks. Keep up the good work.
